package com.mordin.samathascope

data class MetricGlossaryEntry(
  val type: PlotType,
  val plainName: String,
  val abbreviation: String,
  val shortMeaning: String,
  val drivers: String,
  val longMeaning: String,
  val formula: String,
  val canBeFeedbackSource: Boolean,
)

object MetricGlossary {
  private val entries = listOf(
    MetricGlossaryEntry(
      type = PlotType.MEDITATION_PROXY,
      plainName = "Meditation Proxy",
      abbreviation = "MP",
      shortMeaning = "A combined reward proxy for relaxed, alert, clean frontal settling.",
      drivers = "It rises when settledness, alertness, and signal quality are all good together.",
      longMeaning = "This is the main training signal. It is not a claim about meditative attainment; it is a practical feedback proxy that fades down when the signal is drowsy or contaminated.",
      formula = "MeditationProxy = Settledness * Alertness * QualityConfidence",
      canBeFeedbackSource = true,
    ),
    MetricGlossaryEntry(
      type = PlotType.SETTLEDNESS,
      plainName = "Settledness",
      abbreviation = "S",
      shortMeaning = "How much the current frontal pattern looks calm but still organized.",
      drivers = "It rises when alpha-over-beta balance looks more settled without a strong theta-heavy drift toward drowsiness.",
      longMeaning = "Settledness tries to reflect relaxed-but-awake frontal settling. It is intentionally different from simple slowing or drowsiness.",
      formula = "Settledness = sigmoid(z(ABR) - 0.5*z(TAR))",
      canBeFeedbackSource = true,
    ),
    MetricGlossaryEntry(
      type = PlotType.CONTROL,
      plainName = "Control",
      abbreviation = "C",
      shortMeaning = "A proxy for stable cognitive control versus drifting.",
      drivers = "It rises when theta-to-beta balance is lower than the user's baseline.",
      longMeaning = "Control is a simple frontal control proxy. It should be read as 'more or less stable regulation' rather than a literal attention meter.",
      formula = "Control = sigmoid(-z(TBR))",
      canBeFeedbackSource = true,
    ),
    MetricGlossaryEntry(
      type = PlotType.ALERTNESS,
      plainName = "Alertness",
      abbreviation = "A",
      shortMeaning = "The inverse of the drowsiness model.",
      drivers = "It falls when theta-heavy slowing rises and entropy and alpha-over-beta balance fall in a drowsy direction.",
      longMeaning = "Alertness is a practical wakefulness proxy for this device and montage. It is not a clinical vigilance score.",
      formula = "Alertness = 1 - DrowsyScore",
      canBeFeedbackSource = true,
    ),
    MetricGlossaryEntry(
      type = PlotType.DROWSY_SCORE,
      plainName = "Drowsiness",
      abbreviation = "D",
      shortMeaning = "A frontal slowing proxy that tries to separate sleepy quietness from useful settling.",
      drivers = "It rises with higher TAR, higher TBR, lower entropy, and lower ABR. Brief spikes can happen with eyes-closed slowing or transient low-entropy windows.",
      longMeaning = "This is not a sleep-stage detector. On a single dry FP1 electrode it is best read as 'frontal drowsy-like evidence' rather than proof that the user is falling asleep.",
      formula = "D = sigmoid(1.3*z(TAR) + 0.9*z(TBR) - 0.7*z(Entropy) - 0.4*z(ABR))",
      canBeFeedbackSource = false,
    ),
    MetricGlossaryEntry(
      type = PlotType.ARTEFACT_SCORE,
      plainName = "Artefact Score",
      abbreviation = "AS",
      shortMeaning = "How contaminated the current signal looks.",
      drivers = "It rises with poor contact, blink/transient activity, muscle-like high-frequency activity, clipping, and packet stalls.",
      longMeaning = "This is the main contamination gate. High artefact means the app should stop trusting the state estimate and reduce reward.",
      formula = "A = 0.30*contact + 0.25*emg + 0.20*blink + 0.15*clip + 0.10*stall",
      canBeFeedbackSource = false,
    ),
    MetricGlossaryEntry(
      type = PlotType.QUALITY_CONFIDENCE,
      plainName = "Quality Confidence",
      abbreviation = "QC",
      shortMeaning = "How much confidence the app has that the current window is usable.",
      drivers = "It rises when artefact score is low.",
      longMeaning = "Quality confidence is the clean-signal complement of artefact score. It does not mean the classification is perfect; it means the data are usable enough to trust more.",
      formula = "QualityConfidence = 1 - ArtefactScore",
      canBeFeedbackSource = true,
    ),
    MetricGlossaryEntry(
      type = PlotType.EFFORTFUL_FOCUS_SCORE,
      plainName = "Effortful Focus",
      abbreviation = "F",
      shortMeaning = "A proxy for active re-focusing or deliberate control.",
      drivers = "It rises when beta-related control looks stronger while settled alpha-over-beta balance is not dominant.",
      longMeaning = "Effortful focus is not necessarily better meditation; it often reflects active steering, correction, or task-like control.",
      formula = "F = sigmoid(-0.9*z(ABR) - 0.7*z(TBR) + 0.4*z(logBeta) - 0.2*z(Entropy))",
      canBeFeedbackSource = true,
    ),
    MetricGlossaryEntry(
      type = PlotType.MIND_WANDERING_SCORE,
      plainName = "Mind Wandering",
      abbreviation = "W",
      shortMeaning = "A proxy for reduced control while still awake.",
      drivers = "It rises when TBR increases without the more settled alpha-over-beta pattern.",
      longMeaning = "This is a lightweight awake-drift proxy for live feedback, not a definitive thought-content detector.",
      formula = "W = sigmoid(0.9*z(TBR) - 0.4*z(ABR) - 0.2*z(Entropy))",
      canBeFeedbackSource = false,
    ),
    MetricGlossaryEntry(
      type = PlotType.ESENSE_MEDITATION,
      plainName = "eSense Meditation",
      abbreviation = "EMed",
      shortMeaning = "Vendor telemetry shown for comparison only.",
      drivers = "This value comes from NeuroSky's proprietary eSense pipeline, not the app's classifier.",
      longMeaning = "The app keeps this visible as telemetry but does not use it as ground truth or as the recommended feedback source.",
      formula = "Provided by ThinkGear / NeuroSky",
      canBeFeedbackSource = false,
    ),
    MetricGlossaryEntry(
      type = PlotType.ESENSE_ATTENTION,
      plainName = "eSense Attention",
      abbreviation = "EAtt",
      shortMeaning = "Vendor telemetry shown for comparison only.",
      drivers = "This value comes from NeuroSky's proprietary eSense pipeline, not the app's classifier.",
      longMeaning = "The app keeps this visible as telemetry but does not use it as ground truth or as the recommended feedback source.",
      formula = "Provided by ThinkGear / NeuroSky",
      canBeFeedbackSource = false,
    ),
    MetricGlossaryEntry(
      type = PlotType.RAW,
      plainName = "Raw EEG",
      abbreviation = "Raw",
      shortMeaning = "The incoming unscored EEG waveform.",
      drivers = "This shows the live signal itself before the classifier reduces it to summary features.",
      longMeaning = "Raw EEG is useful for visually spotting clipping, stalls, movement, or unstable contact. It is not normalized and is not used as a feedback source.",
      formula = "Live FP1 raw stream at 512 Hz",
      canBeFeedbackSource = false,
    ),
  ).associateBy { it.type }

  fun entryFor(type: PlotType): MetricGlossaryEntry = entries.getValue(type)

  fun dashboardMetrics(): List<PlotType> = listOf(
    PlotType.MEDITATION_PROXY,
    PlotType.SETTLEDNESS,
    PlotType.CONTROL,
    PlotType.ALERTNESS,
    PlotType.DROWSY_SCORE,
    PlotType.ARTEFACT_SCORE,
    PlotType.QUALITY_CONFIDENCE,
    PlotType.EFFORTFUL_FOCUS_SCORE,
    PlotType.MIND_WANDERING_SCORE,
    PlotType.ESENSE_MEDITATION,
    PlotType.ESENSE_ATTENTION,
  )

  fun feedbackSourceMetrics(): List<PlotType> = dashboardMetrics().filter { entryFor(it).canBeFeedbackSource }

  fun learnEntries(): List<MetricGlossaryEntry> = listOf(
    PlotType.MEDITATION_PROXY,
    PlotType.SETTLEDNESS,
    PlotType.CONTROL,
    PlotType.ALERTNESS,
    PlotType.DROWSY_SCORE,
    PlotType.ARTEFACT_SCORE,
    PlotType.QUALITY_CONFIDENCE,
    PlotType.EFFORTFUL_FOCUS_SCORE,
    PlotType.MIND_WANDERING_SCORE,
    PlotType.ESENSE_MEDITATION,
    PlotType.ESENSE_ATTENTION,
    PlotType.RAW,
  ).map(::entryFor)
}
