package com.mordin.samathascope

data class MetricGlossaryTerm(
  val label: String,
  val meaning: String,
)

data class MetricGlossaryEntry(
  val type: PlotType,
  val plainName: String,
  val abbreviation: String,
  val shortMeaning: String,
  val drivers: String,
  val longMeaning: String,
  val displayFormula: String,
  val plainFormula: String,
  val canBeFeedbackSource: Boolean,
  val interpretiveNote: String = "",
  val terms: List<MetricGlossaryTerm> = emptyList(),
)

object MetricGlossary {
  private val entries = listOf(
    MetricGlossaryEntry(
      type = PlotType.MEDITATION_PROXY,
      plainName = "Meditation Proxy",
      abbreviation = "MP",
      shortMeaning = "A practical reward proxy for relaxed, alert, clean settling.",
      drivers = "It rises when settledness, alertness, and usable signal quality all stay strong together.",
      longMeaning = "This is the main dashboard reward. It is intentionally conservative: contamination and sleepy slowing fade it down so the app does not reward quiet but unusable or drowsy windows.",
      displayFormula = "MP = Settledness × Alertness × Quality Confidence",
      plainFormula = "MeditationProxy = Settledness * Alertness * QualityConfidence",
      canBeFeedbackSource = true,
      interpretiveNote = "This is a reward heuristic for gameplay and basic session trends, not a clinical meditation score. Individual calibration quality affects the reading.",
    ),
    MetricGlossaryEntry(
      type = PlotType.SETTLEDNESS,
      plainName = "Settledness",
      abbreviation = "S",
      shortMeaning = "How much the current frontal pattern looks calm but still organized.",
      drivers = "It rises when alpha-over-beta balance looks more settled without a strong theta-heavy pull toward drowsiness.",
      longMeaning = "Settledness tries to represent relaxed but awake settling. It is not simple slowing, and it is not meant to reward a dull or sleepy state.",
      displayFormula = "S = sigmoid(z(α/β) − 0.5 × z(θ/α))",
      plainFormula = "Settledness = sigmoid(z(ABR) - 0.5*z(TAR))",
      canBeFeedbackSource = true,
      interpretiveNote = "Frontal α/β balance is highly state- and person-specific. The score is z-scored against your own session baseline, so its first few minutes are less stable.",
      terms = listOf(
        MetricGlossaryTerm("α/β (ABR)", "Alpha-over-beta ratio. Higher values often look calmer, as long as they are not paired with sleepy slowing."),
        MetricGlossaryTerm("θ/α (TAR)", "Theta-over-alpha ratio. Higher values can point toward drowsier slowing, so settledness subtracts some of it."),
      ),
    ),
    MetricGlossaryEntry(
      type = PlotType.CONTROL,
      plainName = "Control",
      abbreviation = "C",
      shortMeaning = "A proxy for stable regulation versus drifting.",
      drivers = "It rises when theta-to-beta balance stays lower than the user's baseline.",
      longMeaning = "Control is a compact frontal control proxy. Read it as more or less stable regulation, not as a literal measure of willpower or intelligence.",
      displayFormula = "C = sigmoid(−z(θ/β))",
      plainFormula = "Control = sigmoid(-z(TBR))",
      canBeFeedbackSource = false,
      interpretiveNote = "θ/β regulation patterns overlap with task-demands and mental effort. High control during meditation may reflect active steering more than effortless stability.",
      terms = listOf(
        MetricGlossaryTerm("θ/β (TBR)", "Theta-over-beta ratio. Higher values often look more drifty; lower values tend to look more controlled."),
      ),
    ),
    MetricGlossaryEntry(
      type = PlotType.ALERTNESS,
      plainName = "Alertness",
      abbreviation = "A",
      shortMeaning = "The inverse of the drowsiness model.",
      drivers = "It falls when theta-heavy slowing rises while entropy and alpha-over-beta balance move in a drowsy direction.",
      longMeaning = "Alertness is a practical wakefulness proxy for this device and montage. It is not a clinical vigilance score, but it is useful as a session feedback source because it cleanly separates awake from sleepy quietness.",
      displayFormula = "A = 1 − Drowsiness",
      plainFormula = "Alertness = 1 - DrowsyScore",
      canBeFeedbackSource = true,
      interpretiveNote = "Alertness inherits all limits of the drowsiness model. It is not a clinical vigilance measure and can fluctuate with eyes-closed relaxation even when the user is awake.",
    ),
    MetricGlossaryEntry(
      type = PlotType.DROWSY_SCORE,
      plainName = "Drowsiness",
      abbreviation = "D",
      shortMeaning = "Frontal slowing evidence that tries to separate sleepy quietness from useful settling.",
      drivers = "It rises with higher TAR, higher TBR, lower entropy, and lower ABR. Brief spikes can still happen with eyes-closed slowing or very low-complexity windows.",
      longMeaning = "This is not a sleep-stage detector. On a single dry FP1 electrode it should be read as drowsy-like evidence, not proof that the user is falling asleep.",
      displayFormula = "D = sigmoid(1.3 × z(θ/α) + 0.9 × z(θ/β) − 0.7 × z(H) − 0.4 × z(α/β))",
      plainFormula = "D = sigmoid(1.3*z(TAR) + 0.9*z(TBR) - 0.7*z(Entropy) - 0.4*z(ABR))",
      canBeFeedbackSource = false,
      interpretiveNote = "Drowsy and relaxed patterns are hard to separate at single-electrode FP1 resolution. Brief elevated readings can happen during deep relaxation, not only during drowsiness.",
      terms = listOf(
        MetricGlossaryTerm("θ/α (TAR)", "Theta-over-alpha ratio. When this rises, the window looks more slowed and sleepy."),
        MetricGlossaryTerm("θ/β (TBR)", "Theta-over-beta ratio. Higher values can indicate reduced control and more drowsy-like drift."),
        MetricGlossaryTerm("H (Entropy)", "Spectral entropy over 4-30 Hz. Lower entropy means the spectrum is simpler and more repetitive, which often happens in sleepy slowing."),
        MetricGlossaryTerm("α/β (ABR)", "Alpha-over-beta ratio. Higher values can support settledness; lower values in this model count toward drowsiness."),
      ),
    ),
    MetricGlossaryEntry(
      type = PlotType.ARTEFACT_SCORE,
      plainName = "Artefact Score",
      abbreviation = "AS",
      shortMeaning = "How contaminated the current signal looks.",
      drivers = "It rises with poor contact, blink or transient activity, muscle-like high-frequency activity, clipping, and packet stalls.",
      longMeaning = "This is the main contamination gate. High artefact means the app should stop trusting the state estimate and reduce reward, even if the waveform also looks quiet.",
      displayFormula = "AS = 0.30 × contact + 0.10 × line + 0.25 × EMG + 0.16 × blink + 0.12 × clip + 0.10 × stall",
      plainFormula = "ArtefactScore = 0.30*contact + 0.10*line + 0.25*emg + 0.16*blink + 0.12*clip + 0.10*stall",
      canBeFeedbackSource = false,
      interpretiveNote = "Sitting very still and ensuring good headset contact reduces this significantly. Jaw clenching, forehead tension, and loose electrodes are the most common sources.",
    ),
    MetricGlossaryEntry(
      type = PlotType.QUALITY_CONFIDENCE,
      plainName = "Quality Confidence",
      abbreviation = "QC",
      shortMeaning = "How much the app trusts the current window as usable input.",
      drivers = "It rises when artefact score is low.",
      longMeaning = "Quality confidence is the clean-signal complement of artefact score. It does not mean the classification is perfect; it means the window is usable enough to trust more.",
      displayFormula = "QC = 1 − Artefact Score",
      plainFormula = "QualityConfidence = 1 - ArtefactScore",
      canBeFeedbackSource = false,
      interpretiveNote = "High quality confidence means the window passed artefact screening, not that the classification is correct. Correct classification additionally requires a well-established personal baseline.",
    ),
    MetricGlossaryEntry(
      type = PlotType.EFFORTFUL_FOCUS_SCORE,
      plainName = "Effortful Focus",
      abbreviation = "F",
      shortMeaning = "A proxy for active re-focusing or deliberate correction.",
      drivers = "It rises when beta-related control looks stronger while settled alpha-over-beta balance is not dominant.",
      longMeaning = "Effortful focus is not automatically better meditation. It often reflects steering, correction, or task-like control, so the games use it as a short rescue pulse rather than a constant reward channel.",
      displayFormula = "F = sigmoid(−0.9 × z(α/β) − 0.7 × z(θ/β) + 0.4 × z(log β) − 0.2 × z(H))",
      plainFormula = "F = sigmoid(-0.9*z(ABR) - 0.7*z(TBR) + 0.4*z(logBeta) - 0.2*z(Entropy))",
      canBeFeedbackSource = false,
      interpretiveNote = "Effortful focus during meditation is not automatically better practice. This metric is used as a short rescue pulse in games, not as a sustained reward channel.",
    ),
    MetricGlossaryEntry(
      type = PlotType.MIND_WANDERING_SCORE,
      plainName = "Mind Wandering",
      abbreviation = "W",
      shortMeaning = "A proxy for awake drift, reduced regulation, or loosening attention.",
      drivers = "It rises when theta-over-beta increases without the more settled alpha-over-beta pattern, especially when entropy does not support a clean stable state.",
      longMeaning = "This is a lightweight awake-drift proxy for live feedback, not a thought-content detector. It is most useful as a disorganization axis: more wandering usually means more drift, tangling, sway, or broken continuity in the games.",
      displayFormula = "W = sigmoid(0.9 × z(θ/β) − 0.4 × z(α/β) − 0.2 × z(H))",
      plainFormula = "W = sigmoid(0.9*z(TBR) - 0.4*z(ABR) - 0.2*z(Entropy))",
      canBeFeedbackSource = false,
      interpretiveNote = "Awake drifting is not reliably separable from settled contemplation at single-electrode FP1. Use this as a loose disorganisation proxy, not as a definitive thought-content indicator.",
      terms = listOf(
        MetricGlossaryTerm("θ/β (TBR)", "Theta-over-beta ratio. Higher values often look more drifty or less controlled."),
        MetricGlossaryTerm("α/β (ABR)", "Alpha-over-beta ratio. Stronger settled alpha-over-beta balance pushes mind-wandering evidence back down."),
        MetricGlossaryTerm("H (Entropy)", "Spectral entropy. In this score it helps distinguish awake, varied activity from simplistic sleepy slowing."),
      ),
    ),
    MetricGlossaryEntry(
      type = PlotType.ESENSE_MEDITATION,
      plainName = "eSense Meditation",
      abbreviation = "EMed",
      shortMeaning = "Vendor telemetry shown for comparison only.",
      drivers = "This value comes from NeuroSky's proprietary eSense pipeline, not the app's classifier.",
      longMeaning = "The app keeps this visible as telemetry but does not use it as ground truth or as the recommended feedback source.",
      displayFormula = "Provided by ThinkGear / NeuroSky",
      plainFormula = "Provided by ThinkGear / NeuroSky",
      canBeFeedbackSource = false,
      interpretiveNote = "Vendor eSense values use a proprietary algorithm; methodology is not disclosed. Treat as supplementary context, not as a comparable alternative.",
    ),
    MetricGlossaryEntry(
      type = PlotType.ESENSE_ATTENTION,
      plainName = "eSense Attention",
      abbreviation = "EAtt",
      shortMeaning = "Vendor telemetry shown for comparison only.",
      drivers = "This value comes from NeuroSky's proprietary eSense pipeline, not the app's classifier.",
      longMeaning = "The app keeps this visible as telemetry but does not use it as ground truth or as the recommended feedback source.",
      displayFormula = "Provided by ThinkGear / NeuroSky",
      plainFormula = "Provided by ThinkGear / NeuroSky",
      canBeFeedbackSource = false,
      interpretiveNote = "Vendor eSense values use a proprietary algorithm; methodology is not disclosed. Treat as supplementary context, not as a comparable alternative.",
    ),
    MetricGlossaryEntry(
      type = PlotType.RAW,
      plainName = "Raw EEG",
      abbreviation = "Raw",
      shortMeaning = "The incoming unscored EEG waveform.",
      drivers = "This shows the live signal before the classifier reduces it to summary features.",
      longMeaning = "Raw EEG is useful for visually spotting clipping, stalls, movement, or unstable contact. It is not normalized and is not used as a feedback source.",
      displayFormula = "Live FP1 raw stream at 512 Hz",
      plainFormula = "Live FP1 raw stream at 512 Hz",
      canBeFeedbackSource = false,
      interpretiveNote = "Raw EEG at FP1 combines frontal neural activity with muscle, eye, and contact artefacts. Visual inspection helps confirm signal quality before trusting derived metrics.",
    ),
  ).associateBy { it.type }

  fun entryFor(type: PlotType): MetricGlossaryEntry = entries.getValue(type)

  fun dashboardMetrics(): List<PlotType> = listOf(
    PlotType.MEDITATION_PROXY,
    PlotType.SETTLEDNESS,
    PlotType.CONTROL,
    PlotType.ALERTNESS,
    PlotType.ARTEFACT_SCORE,
    PlotType.EFFORTFUL_FOCUS_SCORE,
    PlotType.MIND_WANDERING_SCORE,
    PlotType.ESENSE_MEDITATION,
    PlotType.ESENSE_ATTENTION,
  )

  fun feedbackSourceMetrics(): List<PlotType> = listOf(
    PlotType.MEDITATION_PROXY,
    PlotType.SETTLEDNESS,
    PlotType.ALERTNESS,
  )

  fun learnEntries(): List<MetricGlossaryEntry> = listOf(
    PlotType.MEDITATION_PROXY,
    PlotType.SETTLEDNESS,
    PlotType.CONTROL,
    PlotType.ALERTNESS,
    PlotType.DROWSY_SCORE,
    PlotType.ARTEFACT_SCORE,
    PlotType.QUALITY_CONFIDENCE,
    PlotType.EFFORTFUL_FOCUS_SCORE,
    PlotType.MIND_WANDERING_SCORE,
    PlotType.ESENSE_MEDITATION,
    PlotType.ESENSE_ATTENTION,
    PlotType.RAW,
  ).map(::entryFor)
}
